stages:
  - mirror

mirror-github:
  stage: mirror
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - 'git -c "credential.helper=" -c "http.extraHeader=Authorization: token ${GH_MIRROR_TOKEN}" push https://github.com/nurazhardotcom/${CI_PROJECT_NAME}.git HEAD:main --force --verbose'
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  allow_failure: true
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 0
